# Generated by Django 4.1 on 2022-08-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=20),
        ),
    ]
