# Generated by Django 4.1 on 2022-08-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
