# Generated by Django 4.1 on 2022-08-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0004_user_is_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
