# Generated by Django 4.1 on 2022-08-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scope', '0005_delete_task_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=120)),
                ('task_id', models.IntegerField()),
                ('task_status', models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Pending', 'Pending')], default='Completed', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_date', models.DateField()),
                ('approval_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Approved', max_length=20)),
                ('assigned_manager', models.CharField(max_length=50)),
                ('task_description', models.CharField(max_length=360)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=60)),
                ('user_id', models.IntegerField()),
                ('is_superuser', models.BooleanField(default=False)),
                ('department', models.CharField(max_length=60)),
                ('designation', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=20)),
                ('is_manager', models.BooleanField(default=False)),
            ],
        ),
    ]
