# Generated by Django 4.1 on 2022-08-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0011_user_department_user_designation_user_manager_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
