# Generated by Django 4.1 on 2022-08-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0012_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='manager_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
